services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: mygasuser
      POSTGRES_PASSWORD: mygaspassword
      POSTGRES_DB: gas_sensor
      TZ: Asia/Seoul
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - gas_network

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - gas_network

  sensor_simulator:
    image: devimoong/iot-platform:sensor_simulator
    container_name: gas_sensor_simulator
    environment:
      MQTT_BROKER_URL: mqtt://mqtt-broker:1883
    depends_on:
      - mqtt-broker
    networks:
      - gas_network
    command: python3 main.py

  app:
    image: devimoong/iot-platform:app
    container_name: gas_sensor_app
    environment:
      DATABASE_URL: postgres://mygasuser:mygaspassword@db:5432/gas_sensor
    depends_on:
      - db
      - sensor_simulator
    ports:
      - "3000:3000"
    networks:
      - gas_network
    command: npm start

  streamlit:
    image: devimoong/iot-platform:dashboard
    container_name: streamlit_dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=gas_sensor
      - DB_USER=mygasuser
      - DB_PASSWORD=mygaspassword
    networks:
      - gas_network

networks:
  gas_network:
    driver: bridge
